# Generated by Django 5.0 on 2024-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack_type', models.CharField(max_length=20)),
                ('power', models.PositiveSmallIntegerField()),
                ('status_effect', models.CharField(blank=True, max_length=20, null=True)),
                ('status_effect_chance', models.FloatField(default=0)),
                ('status_change', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_change', models.IntegerField(blank=True, null=True)),
                ('stat_change_target', models.CharField(default='self', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='defense_sp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='special_defense',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type2',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attacks',
            field=models.ManyToManyField(blank=True, to='pokedex.attack'),
        ),
    ]
